### PR TITLE
Fix string formatting in TestCases.ValidWildcard.

### PR DESCRIPTION
**Pull request by coruus**
The "%" formatting operator has a higher precedence than the "+" operator.
This results in an unhelpful exception if a TLD is passed in.

(My editor also stripped some trailing whitespace.)

### CODE REVIEW

**Comment by coruus** [comment]
These commits are a start on cleaning up the code to conform to Python convention. 

(Btw, you might, in future, find it more convenient to use pyasn1's **getitem** methods, rather than the .getComponentBy methods. I'm not sure whether they're in the rather old PyPi version, but a recent cvs-fast-export is at https://github.com/coruus/pyasn1{,-modules} if you like.)

**Comment by yymax** [comment]
Hi, coruus. Thanks for the comments and help. I started on python for less than a year so I am not aware of the proper convention. (I programmed in C a lots for my previous projects...) Also, how can I take a look on your changes before I merge it? Do I just git pull origin master, then git push origin master? (Sorry, yesterday is my first time to use git.)

**Comment by coruus** [comment]
Oh, no problem; it's generally quite good Python.

I generally do something like:

```
# Add the other GitHub user's repo as a remote.
git remote add coruus https://github.com/coruus/x509test
# Pull from the other repo.
git pull --all
# Checkout their master branch to a new tracking branch named.
git checkout -b coruus --track coruus/master
# Test changes to make sure they don't completely break everything.
# Go to Github and click "Merge pull request" on this page.
git pull --all
git checkout master
# Test again, fix bugs, etc.; possibly create and push a new commit.
```

(There are many slightly better but vastly more complicated ways of doing things in Git.)

Also, if you use OSX, I highly recommend getting [GitX](http://rowanj.github.io/gitx/).

**Comment by yymax** [comment]
Okay, thanks. I have checked the code and it looks like you are still working on some of the files. (The indentation in ValidCert class seems to be a little bit off.) I will perform a comprehensive QA after you are done with all the files. Then I will push the merge button and let the magic happens.

**Comment by yymax** [comment]
And if possible, can you change the SOFTWARE_VERSION macro in Definitions.py to "0.1.1" after you are done?

**Pull request merged**
